# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 408910836c883102b197c6f2a7f0106e93459fc43e0de521222ec5f32fd1f1a4c92e2e4858fabad83545e4833dbe79cbd83f5139503dd918f00225a9d88029b4

test:
  secret_key_base: 7388a16c1ffda0193cb98420bfe4ebce555f7b6cfffc1d24cd257a2f67f0854eb24ff0cce2644eafca15acda2aa405e6e48aaed13ede9157b75adb93a7a5ab96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
